In [1]:
test_input_data_shape = [128, 5]
test_rnn_size = 256
test_embed_dim = 300
test_rnn_layer_size = 2
test_vocab_size = 27
test_input_data_shape + [test_vocab_size]

[128, 5, 27]

In [2]:
[2, 2] + [1, 2]

[2, 2, 1, 2]

In [1]:
import numpy as np

In [5]:
a = np.zeros((4,6))
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
a.shape

(4, 6)

In [7]:
a[:][:].shape

(4, 6)

In [8]:
a[1:3][:].shape

(2, 6)

In [9]:
a[:][1:3].shape

(2, 6)

In [10]:
a[:][1:3]

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
a[1:3][:]

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

In [14]:
b[:][0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b[:][:][0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[:, 0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [22]:
b[:-1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b[:,-1] = b[:,0]
b

array([[ 1,  2,  1],
       [ 4,  5,  4],
       [ 7,  8,  7],
       [10, 11, 10]])

In [2]:
x = np.array([[[2, 6, 5], [7, 6, 5], [4, 6, 7]],
              [[4, 6, 7], [1, 4, 5], [8, 9, 5]],
              [[7, 6, 5], [4, 2, 5], [7, 1, 5]]])

In [12]:
y = x.argsort()[:,:,-1]
y

array([[1, 0, 2],
       [2, 2, 1],
       [0, 2, 0]])

In [ ]:
z= for i in y